#ifndef CPU_CFG_MODULE_PRESENT
#define CPU_CFG_MODULE_PRESENT

#define CPU_CFG_NAME_EN DEF_ENABLED
#define CPU_CFG_NAME_SIZE 16

#define CPU_CFG_TS_32_EN DEF_DISABLED
#define CPU_CFG_TS_64_EN DEF_DISABLED
#define CPU_CFG_TS_TMR_SIZE CPU_WORD_SIZE_32

#define CPU_CFG_INT_DIS_MEAS_OVRHD_NBR 1u

#define CPU_CFG_LEAD_ZEROS_ASM_PRESENT

#define CPU_CFG_CACHE_MGMT_EN DEF_DISABLED

#endif