#ifndef OS_CFG_APP_H
#define OS_CFG_APP_H

#define OS_CFG_MSG_POOL_SIZE 100u
#define OS_CFG_ISR_STK_SIZE 100u
#define OS_CFG_TASK_STK_LIMIT_PCT_EMPTY 10u

#define OS_CFG_IDLE_TASK_STK_SIZE 128u

#define OS_CFG_INT_Q_SIZE 10u
#define OS_CFG_INT_Q_TASK_STK_SIZE 100u

#define OS_CFG_STAT_TASK_PRIO (OS_CFG_PRIO_MAX - 3u)
#define OS_CFG_STAT_TASK_RATE_HZ 10u
#define OS_CFG_STAT_TASK_STK_SIZE 100u

#define OS_CFG_TICK_RATE_HZ 100u
#define OS_CFG_TICK_TASK_PRIO 1u
#define OS_CFG_TICK_TASK_STK_SIZE 128u

#define OS_CFG_TMR_TASK_PRIO 11u
#define OS_CFG_TMR_TASK_RATE_HZ 10u
#define OS_CFG_TMR_TASK_STK_SIZE 1024u

#endif
